- name: Acte 3 - congigure csr1000 dhcp
  # On va agir sur l'hôte csr1000 dans cet acte
  hosts: csr1000
  # Passe l'étape permettant de récupérer des informations sur
  #   l'hôte pour gagner du temps
  gather_facts: false

  # Liste des tâches associées à notre Acte
  tasks:
    - name: Configuration DHCP
      cisco.ios.ios_config:
        lines:
        - no ip dhcp pool dhcppool
        - ip dhcp pool dhcppool
        - network 192.168.2.0 255.255.255.0
        - default-router 192.168.2.1
        - exit
        - service dhcp
