 - name: Acte 1 - essai csr1000
  # On va agir sur l'hôte csr1000 dans cet acte
   hosts: csr1000
  # Passe l'étape permettant de récupérer des informations sur
  #   l'hôte pour gagner du temps
   gather_facts: false

  # Liste des tâches associées à notre Acte
   tasks:
     - name: Configuration de dhcp
       cisco.ios.ios_config:
         lines:
           - ip dhcp excluded-address 192.168.0.1 192.168.0.50
           - ip dhcp pool Floor1DHCP
           - network 192.168.0.0 255.255.255.0
           - default-router 192.168.0.1
           - dns-server 192.168.0.1
