 - name: Acte 1 - essai csr1000
  # On va agir sur l'hôte csr1000 dans cet acte
   hosts: csr1000
  # Passe l'étape permettant de récupérer des informations sur
  #   l'hôte pour gagner du temps
   gather_facts: false

  # Liste des tâches associées à notre Acte
   tasks:
     - name: Configuration de g1
       cisco.ios.ios_config:
         lines:
         - ip nat outside
         parents: int g1
     - name: Configuration de g2
       cisco.ios.ios_config:
         lines:
         - ip nat inside
         parents: int g2
     - name: Configuration de g3
       cisco.ios.ios_config:
         lines:
         - ip nat inside
         parents: int g3
     - name: Configuration de g4
       cisco.ios.ios_config:
         lines:
         - ip nat inside
         parents: int g4

