 - name: Acte 1 - essai csr1000
  # On va agir sur l'hôte csr1000 dans cet acte
   hosts: csr1000
  # Passe l'étape permettant de récupérer des informations sur
  #   l'hôte pour gagner du temps
   gather_facts: false

  # Liste des tâches associées à notre Acte
   tasks:
    - name: Merge provided configuration with device configuration
      cisco.ios.ios_l3_interfaces:
        config:
          - name: GigabitEthernet2
            ipv4:
            - address: 192.168.2.1/24
          - name: GigabitEthernet3
            ipv4:
            - address: 192.168.3.1/24
          - name: GigabitEthernet4
            ipv4:
            - address: 192.168.4.1/24
        state: merged
